### ISSUE TITLE
Problem when playing unsupported files?

### ISSUE THREAD

**Issue by Unnepad** [stsaz/phiola#33]
Lately, I've noticed some problems when trying to play unsupported files on GUI (like image or text files).

The normal behaviour is that it should display a notification describing the error, and play the next file if possible.

However, after installing newer versions (I think after rc23) there's some issues. On some instances, the program used to freeze and consume a lot of memory. On others, it just exits or doesn't show a notification.

CLI works fine, so it must be an issue with the GUI.

**Comment by Unnepad** [comment]
![Captura de pantalla_20240513_121909](https://github.com/stsaz/phiola/assets/169686846/28987611-9c7e-4c56-8526-d203f4240b99)

This is a example of a error message when using the GUI through the terminal.

**Comment by stsaz** [comment]
Hi!

Here's what happened:
* phiola wrote some incorrect values to your `~/.config/phiola/gui.conf`
* phiola then passes these values to GTK to set the window size of "Logs" window, but instead of clipping the values or just ignoring them, this results in a crash on Wayland (this looks like a GTK or Wayland bug, BTW)

To fix the problem:
* Remove your `~/.config/phiola/gui.conf` file (or remove huge window position values from there manually)
* And then use `2.1-beta1` version (it won't write incorrect window position values to your `gui.conf`, because I fixed that already)

P.S.
Do you have the latest GTK3 and Wayland packages installed?  We could try to report this issue to them, but I don't currently have the latest versions to test.

**Comment by Unnepad** [comment]
I removed gui.conf, installed 2.1-beta1 and it seems to be fixed :)
It's weird, though, because I previously installed 2.1-beta1. I guess the file wasn't automatically removed.

I'm using Fedora 40 (KDE), so I'm assuming I have the latest Wayland/GTK3 packages.
