### ISSUE TITLE
Please share the readme gui theme.conf

### ISSUE THREAD

**Issue by superuser7777** [stsaz/phiola#48]
Could you please share the GUI theme.conf in phiola's readme?
I am in a Windows environment, but would like the KDE/Linux version.
It's very beautiful in full dark mode.

![image](https://github.com/stsaz/phiola/blob/screenshots/phiola-gui-screenshot-android-kdelinux-windows.png)

**Comment by stsaz** [comment]
Hi!  Dark theme on Linux is handled entirely by GTK library - that's why it's so nice.  On Windows, on the other hand, it must be handled by the application, and currently it's incomplete and somewhat ugly.  It requires much more work to draw all UI controls manually -- it's very hard for me.  The way I see it - MS doesn't want to make its Windows users happy with nicely colored dark mode native (non .NET) apps.  It is what it is.

**Comment by superuser7777** [comment]
hmmm... I see.
Thank you, I understand.
