### ISSUE TITLE
Normalize files

### ISSUE THREAD

**Issue by Ducke1001** [stsaz/phiola#57]
In your wiki there is the option -gain to change the volume of a file. But it looks like this option is not implemented, right?
> phiola "Deep House Special Mix.mp3" -gain 6 -o test.mp3
 #3012 ERROR  unknown option '-gain'. Use '-h' for usage info.

It would be great to be able to use this option to normalize the files.

**Comment by stsaz** [comment]
There are several mistakes here:
* you shoud use `convert` command when converting files -- by default phiola starts in playback mode
* MP3 encoding is disabled, so `-gain` with `-o .mp3` won't work

So you should use something like this:

`phiola convert "Deep House Special Mix.mp3" -gain 6 -o test.ogg`

**Comment by Ducke1001** [comment]
Sorry, I must have mixed that up.
Is it possible to combine gain with convert -copy and overwrite the file?

**Comment by stsaz** [comment]
> Is it possible to combine gain with convert -copy and overwrite the file?

No, because `-gain` (i.e. changing the volume level of audio samples) must be applied to uncompressed (decoded) audio while `-copy` switch can only copy compressed (encoded) data.  So either you just copy MP3 frames without changing volume, or you decode, apply volume, and then encode again.  But keep in mind that re-encoding compressed audio files will slightly decrease original audio quality.

Another approach is to use some ID3v2 tags (e.g. replay gain) that will instruct the decoder to apply volume at runtime.  But currently phiola doesn't support that.

**Comment by Ducke1001** [comment]
Ah, OK. That might be a great feature for the future.

**Comment by stsaz** [comment]
Support for replay-gain is mentioned in #31, closing this.
